### PR TITLE
build .rpm and .deb packages to automatically install and configure frankenphp

### PR DESCRIPTION
**Pull request by henderkes**
see https://github.com/dunglas/frankenphp/issues/1459

requires [fpm](https://fpm.readthedocs.io/) but it works perfectly well to automatically configure frankenphp

we could let this script run in the centos 7 container on deployment.

### CODE REVIEW

**Comment by DubbleClick** [comment]
even better, once https://github.com/crazywhalecc/static-php-cli/pull/673 is merged, we can --build-shared=xdebug in the glibc command and automatically release `frankenphp-xdebug-$(FRANKENPHP_VERSION` and `frankenphp-ffi-$(FRANKENPHP_VERSION`.

File: static-builder-gnu.Dockerfile [hunk 1]
```diff
@@ -112,8 +112,9 @@ ENV SPC_LIBC='glibc'
 ENV SPC_CMD_VAR_PHP_MAKE_EXTRA_LDFLAGS_PROGRAM='-Wl,-O3 -pie'
 ENV SPC_CMD_VAR_PHP_MAKE_EXTRA_LIBS='-ldl -lpthread -lm -lresolv -lutil -lrt'
 ENV SPC_OPT_DOWNLOAD_ARGS='--ignore-cache-sources=php-src'
-ENV SPC_OPT_BUILD_ARGS=''
+ENV SPC_OPT_BUILD_ARGS='--with-config-file-path=/etc/frankenphp/php.ini --with-config-file-scan-dir=/etc/frankenphp/php.d'
 ENV SPC_REL_TYPE='binary'
+ENV EXTENSION_DIR='/usr/lib64/frankenphp/modules'
```
Comment (DubbleClick) [inline static-builder-gnu.Dockerfile:117]: so this one is a doozy, because the default paths are:

```
; Ubuntu/Debian: /usr/lib/php/{PHP_VERSION}/
; RHEL: /usr/lib64/php/modules
; Alpine: /usr/lib/php{PHP_VERSION}/modules
; where {PHP_VERSION} is 84 for php 8.4
```

I cannot think of a way to build these for different paths without rebuilding and I also cannot think of a single path that we could use on every distro. Maybe `/usr/bin/frankenphp-ext`? Most definitely bad practise...

Comment (DubbleClick) [reply static-builder-gnu.Dockerfile:117]: Wait, `/usr/lib/frankenphp/modules` should be fine on each distribution. It may be slightly off best-practise for RHEL since extensions would be 64 bit dll's and would typically go into /usr/lib64, but this would keep the location unified.

File: build-packages.sh [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+	PrivateTmp=true
+	ProtectHome=true
+	ProtectSystem=full
+	AmbientCapabilities=CAP_NET_BIND_SERVICE
+
+	[Install]
+	WantedBy=multi-user.target
+EOF
+
+cat <<EOF >dist/Caddyfile
```
[the remark this answers is not in the document]
Comment (DubbleClick) [reply build-packages.sh:63]: This Caddyfile should point to a set location like `/usr/share/caddy` or `/usr/share/frankenphp` because it's a system installation. Making it relative to the binary doesn't make a lot of sense, since it will sit in /usr/bin, where webpages will definitely not go.

**Comment by DubbleClick** [comment]
success! to get them from the container after building we can run 

```console
docker run --rm static-builder-gnu sh -c "ls /go/src/app/dist | grep '^frankenphp'" | xargs -I {} sh -c 'docker cp $(docker create static-builder-gnu):/go/src/app/dist/{} ./{}'
```

**Comment by DubbleClick** [comment]
@dunglas I'm happy with this now. Prepared things for when we merge shared extension support into static-php-cli as well.

File: build-packages.sh [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+
+glibc_version=$(ldd -v "$bin" | awk '/GLIBC_/ {gsub(/[()]/, "", $2); print $2}' | grep -v GLIBC_PRIVATE | sed 's/GLIBC_//' | sort -V | tail -n1)
+cxxabi_version=$(strings "$bin" | grep -oP 'CXXABI_\d+\.\d+(\.\d+)?' | sed 's/CXXABI_//' | sort -V | tail -n1)
+
+fpm -s dir -t deb -n frankenphp -v "${FRANKENPHP_VERSION}" \
+	--config-files /etc/frankenphp/Caddyfile \
+	--config-files /etc/frankenphp/php.ini \
+	--depends "libc6 (>= ${glibc_version})" \
+	--depends "libstdc++6 (>= ${cxxabi_version})" \
+	--deb-suggests libcap2-bin \
```
Comment (DubbleClick) [inline build-packages.sh:88]: caddy actually does not set port 80/443 free to use for non-root users, so we're slightly off from the standard here. I think suggesting the package and printing a warning if it isn't installed is still fair, though.

fedora derivatives have libcap installed by default and caddys default installation sets it as a net_bind_service

File: package/etc/php.ini [hunk 4]
```diff
@@ -0,0 +1,1870 @@
+﻿[PHP]
```
Comment (dunglas) [inline package/etc/php.ini:1]: Shouldn't we ship the prod and dev version? Couldn't we copy them from
the PHP source tree at build time instead of copying them in our Git repo?

File: package/Caddyfile [hunk 5]
```diff
@@ -0,0 +1,53 @@
+﻿# The Caddyfile is an easy way to configure your Caddy web server.
```
Comment (dunglas) [inline package/Caddyfile:1]: That would be nice to use the same Caddyfile in every distributions, with the same features enabled.

File: caddy/frankenphp/Caddyfile [hunk 6]
```diff
@@ -43,3 +45,9 @@
 
 	php_server
 }
+
+# As an alternative to editing the above site block, you can add your own site
+# block files in the Caddyfile.d directory, and they will be included as long
+# as they use the .caddyfile extension.
+
+import Caddyfile.d/*.caddyfile
```
Comment (dunglas) [inline caddy/frankenphp/Caddyfile:53]: WDYT @mholt @francislavoie, is this a good Caddy practice?

File: package/content/example.php [hunk 7]
```diff
@@ -0,0 +1,140 @@
+﻿<?php
```
Comment (dunglas) [inline package/content/example.php:1]: Could we reduce or remove the provided demo files?
Could we also share them between the Docker images and the packages?

@ginifizz will take a look to the graphic design part.

Comment (dunglas) [inline package/content/example.php:1]: Could we reduce or remove the provided demo files?
Could we also share them between the Docker images and the packages?

@ginifizz will take a look to the graphic design part.

**Review by dunglas — CHANGES_REQUESTED** [review]
This is AWESOME.

I left some minor comments. I also think we should ensure that the experience is as similar as possible between the Docker images, the Brew package and the Linux packages (demo files, `php.ini`, `Caddyfile` etc) to simply the maintenance and support.

File: caddy/frankenphp/Caddyfile (hunk 6 above)
Comment (DubbleClick) [reply caddy/frankenphp/Caddyfile:53]: This comes from the caddy packages, so I would hope so.

I've adopted it since and it has been a good decision. Separation of concerns, which is also why I'm working on https://github.com/dunglas/frankenphp/issues/1490.

File: package/etc/php.ini (hunk 4 above)
Comment (DubbleClick) [reply package/etc/php.ini:1]: Yes, good idea. I'll have to remember to change the Dockerfile to remove sources after building packages.

File: static-builder-gnu.Dockerfile [hunk 8]
```diff
@@ -112,12 +114,27 @@ ENV SPC_LIBC='glibc'
...
 ENV SPC_REL_TYPE='binary'
+ENV EXTENSION_DIR='/usr/lib/frankenphp/modules'
 
 # not sure if this is needed
 ENV COMPOSER_ALLOW_SUPERUSER=1
 
+# install tools to build packages, if requested - needs gcc 10
+RUN if [ "${BUILD_PACKAGES}" != "" ]; then \
+        yum install -y make bzip2 openssl-devel libffi-devel zlib-devel libyaml libyaml-devel rpm-build && \
+        curl -o ruby.tar.gz -fsSL https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.2.tar.gz && \
```
[the remark this answers is not in the document]
Comment (DubbleClick) [reply static-builder-gnu.Dockerfile:127]: I ran into compilation errors when I initially tried 3.4, but maybe that was because I also tried to build with system gcc 4.8.5. I'll see if I can update it.

File: package/Caddyfile [hunk 9]
```diff
@@ -0,0 +1,53 @@
...
+	#	# Extra directives
+	#	{$MERCURE_EXTRA_DIRECTIVES}
+	#}
+	#vulcain
+
+	{$CADDY_SERVER_EXTRA_DIRECTIVES}
+
+	php_server
+}
+
```
[the remark this answers is not in the document]
Comment (DubbleClick) [reply package/Caddyfile:53]: Can we please add a .editorconfig file? 😅

**Comment by DubbleClick** [comment]
I had to switch to a frankenphp user, uninstalling frankenphp or caddy would automatically remove the other's user otherwise.

File: package/Caddyfile (hunk 5 above)
Comment (DubbleClick) [reply package/Caddyfile]: I don't think it makes sense to enable a worker by default in the docker Caddyfile. There's no example project (and it makes no sense to ship one either).

File: package/debian/postinst.sh [hunk 10]
```diff
@@ -0,0 +1,61 @@
...
+	# Restart only if it was already started
+	if [ -d /run/systemd/system ]; then
+		systemctl --system daemon-reload >/dev/null || true
+		if [ -n "$2" ]; then
+			deb-systemd-invoke try-restart frankenphp.service >/dev/null || true
+		fi
+	fi
+fi
+
+HOME=~frankenphp frankenphp trust
```
Comment (DubbleClick) [inline package/debian/postinst.sh:61]: I don't have the faintest idea how caddy works around not having to do this. Or maybe they do and I simply cannot find it in the install scripts.

**Comment by DubbleClick** [comment]
We've merged dynamic extension support into static-php-cli, by the way. Should I put that into this PR and also build a frankenphp-xdebug package that depends on the frankenphp package?

For that, I actually have a question - is it possible to load php with and without xdebug and route the request depending on whether a XDEBUG_SESSION header is set?

Right now I check for (pseudocode, can't check atm)
```caddy
route {
    @xdebug header *XDEBUG_SESSION*
    php_fastcgi @xdebug /path/to/www.sock
    php
}
``` where php_fpm has xdebug loaded and frankenphp doesn't.

File: docs/tr/config.md [hunk 11]
```diff
@@ -1,163 +1,163 @@
...
-
-Docker imajını kullanırken, hata ayıklama modunu etkinleştirmek için `CADDY_GLOBAL_OPTIONS` ortam değişkenini `debug` olarak ayarlayın:
-
-```console
-docker run -v $PWD:/app/public \
-    -e CADDY_GLOBAL_OPTIONS=debug \
-    -p 80:80 -p 443:443 -p 443:443/udp \
-    dunglas/frankenphp
-```
+# Konfigürasyon
```
Comment (dunglas) [inline docs/tr/config.md:1]: There is an end of line problem (CRLF?)

File: package/content/example.php [hunk 12]
```diff
@@ -0,0 +1,140 @@
+<?php
+$requestCount = $i ?? 0;
+$requestTime = $duration ?? 0;
+?>
+
+<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
```
Comment (dunglas) [inline package/content/example.php:6]: Can you please remove this file for now? (or at least switch to HTML5)?

File: package/content/public/index.php [hunk 13]
```diff
@@ -0,0 +1,14 @@
+<?php
```
Comment (dunglas) [inline package/content/public/index.php:1]: Same here

File: package/debian/frankenphp.service [hunk 14]
```diff
@@ -0,0 +1,27 @@
+# See https://caddyserver.com/docs/install for instructions.
+#
+# WARNING: This service does not use the --resume flag, so if you
+# use the API to make changes, they will be overwritten by the
+# Caddyfile next time the service is restarted. If you intend to
```
Comment (dunglas) [inline package/debian/frankenphp.service:5]: The end of the last sentence is missing?

File: package/debian/postinst.sh [hunk 15]
```diff
@@ -0,0 +1,61 @@
...
+			--home-dir /var/lib/frankenphp \
+			--shell /usr/sbin/nologin \
+			--comment "FrankenPHP web server" \
+			frankenphp
+	fi
+	if getent group www-data >/dev/null; then
+		usermod -aG www-data frankenphp
+	fi
+
+	# handle cases where package was installed and then purged;
```
Comment (dunglas) [inline package/debian/postinst.sh:22]:
```suggestion
	# Handle cases where package was installed and then purged;
```

File: package/rhel/postinstall.sh [hunk 16]
```diff
@@ -0,0 +1,26 @@
+#!/bin/bash
+
+if [ "$1" -eq 1 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then
+	# Initial installation
+	/usr/lib/systemd/systemd-update-helper install-system-units frankenphp.service || :
+fi
+
+if [ -x /usr/sbin/getsebool ]; then
+	# connect to ACME endpoint to request certificates
```
Comment (dunglas) [inline package/rhel/postinstall.sh:9]:
```suggestion
	# Connect to ACME endpoint to request certificates
```

Same for all comments for consistency

File: static-builder-gnu.Dockerfile [hunk 17]
```diff
@@ -115,12 +117,27 @@ ENV SPC_LIBC='glibc'
 ENV SPC_CMD_VAR_PHP_MAKE_EXTRA_LDFLAGS_PROGRAM='-Wl,-O3 -pie'
 ENV SPC_CMD_VAR_PHP_MAKE_EXTRA_LIBS='-ldl -lpthread -lm -lresolv -lutil -lrt'
 ENV SPC_OPT_DOWNLOAD_ARGS='--ignore-cache-sources=php-src'
-ENV SPC_OPT_BUILD_ARGS=''
+ENV SPC_OPT_BUILD_ARGS='--with-config-file-path=/etc/frankenphp/php.ini --with-config-file-scan-dir=/etc/frankenphp/php.d'
```
Comment (dunglas) [inline static-builder-gnu.Dockerfile:120]: Do we really need to change the defaults? If so, we'll have to update the docs too

**Review by dunglas — CHANGES_REQUESTED** [review]
This looks almost good to me, but I'm far from being a specialist of packaging.

We'll have to setup package repositories after that, right?

File: package/debian/frankenphp.service (hunk 14 above)
Comment (DubbleClick) [reply package/debian/frankenphp.service:5]: Oh, I didn't remove enough. The official caddy package ships with two services - caddy.service and caddy-api.service. The last sentence was a note to use the caddy-api service to make live config changes.

File: static-builder-gnu.Dockerfile (hunk 17 above)
Comment (DubbleClick) [reply static-builder-gnu.Dockerfile:120]: The default for php is `/etc/php.ini` and `/etc/php.d` or `/etc/php/conf.d` depending on the distro. I doubt we wish to use those directories as we'd couple our frankenphp changes to those of the system php package. There are too many reasons why this is a terrible idea.

When compiling php without `--with-config-file-path` it chooses `/usr/local/php/php.ini` and a different additional path depending on the system it was compiled on. That default is not in line with any system installation you would expect from a rpm/deb package. My only other idea for this was `/etc/frankenphp.ini` and `/etc/frankenphp.d`, but that would suggest frankenphp is something different than php, which it isn't.

File: build-packages.sh [hunk 18]
```diff
@@ -0,0 +1,110 @@
...
+fi
+
+if [[ ! "${FRANKENPHP_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+	echo "Warning: FRANKENPHP_VERSION must be set to X.Y.Z (e.g. 1.5.1), got '${FRANKENPHP_VERSION}'"
+	echo "Falling back to non-release version 0.0.0"
+	FRANKENPHP_VERSION=0.0.0
+fi
+
+mkdir -p package/empty
+[ -f ./dist/static-php-cli/source/php-src/php.ini-production ] && cp -f ./dist/static-php-cli/source/php-src/php.ini-production ./package/etc/php.ini
```
[the remark this answers is not in the document]
Comment (DubbleClick) [reply build-packages.sh:61]: >What php.ini are using the official packages by default? Maybe should we be in sync with their behaviors?

Now here's the kicker, they don't ship the php.ini-production or php.ini-development but create the php.ini file that I initially committed into the package folder.

**Comment by DubbleClick** [comment]
> This looks almost good to me, but I'm far from being a specialist of packaging.
> 
> We'll have to setup package repositories after that, right?

Not necessarily. `dnf` and `apt` can both install repositories directly from a url.

`dnf install https://github.com/dunglas/frankenphp/releases/latest/frankenphp-1.5.1-1.rpm`.

Alternatively we could follow caddy's approach on distros where other package repositories do not have a caddy package and create our own package registry. Then people would have to `dnf install https://dunglas.dev/packages` followed by `dnf install frankenphp`. I think the latter is outside the scope of this for now because it's not related to the creation of the packages.

File: package/content/example.php (hunk 12 above)
Comment (DubbleClick) [reply package/content/example.php:6]: I copied this from `dnf install caddy`'s index.html file.

File: static-builder-gnu.Dockerfile (hunk 17 above)
Comment (DubbleClick) [reply static-builder-gnu.Dockerfile:120]: To expand on this, `/usr/local/etc/` is the folder for user, not system installations of self-compiled software. FrankenPHP installed from a package should definitely not reside there - what if the user compiles and installs php themselves? Suddenly our frankenphp package is broken.

**Comment by DubbleClick** [comment]
I've tried to unify the php paths from the docker images and the static binaries/system installations, but that throws up more problems than it solves. php from the docker images is inherently not built by us and uses all sorts of directories that are different from the ones we (should) use for the static versions.

**Comment by DubbleClick** [comment]
As for the default project installed into `/usr/share/frankenphp`, I'll leave this open to you. What files do you want installed? Do you want worker mode enabled by default?

I think it's easier if you make the changes yourself. You have push access to the branch of this pr.

File: build-packages.sh [hunk 19]
```diff
@@ -0,0 +1,110 @@
...
+		export FRANKENPHP_VERSION
+
+		git checkout "v${FRANKENPHP_VERSION}"
+	else
+		git checkout "${FRANKENPHP_VERSION}"
+	fi
+fi
+
+if [[ ! "${FRANKENPHP_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+	echo "Warning: FRANKENPHP_VERSION must be set to X.Y.Z (e.g. 1.5.1), got '${FRANKENPHP_VERSION}'"
```
Comment (dunglas) [inline build-packages.sh:55]: We should even error if the format isn't valid.

File: caddy/frankenphp/Caddyfile [hunk 20]
```diff
@@ -1,3 +1,8 @@
+# The Caddyfile is an easy way to configure your Caddy web server.
```
Comment (dunglas) [inline caddy/frankenphp/Caddyfile:1]:
```suggestion
# The Caddyfile is an easy way to configure FrankenPHP and the Caddy web server.
```

File: caddy/frankenphp/Caddyfile [hunk 21]
```diff
@@ -1,3 +1,8 @@
...
+#
+# https://caddyserver.com/docs/caddyfile
+# https://frankenphp.dev/docs/config
```
Comment (dunglas) [inline caddy/frankenphp/Caddyfile:4]:
```suggestion
# https://frankenphp.dev/docs/config
# https://caddyserver.com/docs/caddyfile
```

File: docs/config.md [hunk 22]
```diff
@@ -2,15 +2,20 @@
...
 
-In [the Docker images](docker.md), the `Caddyfile` is located at `/etc/caddy/Caddyfile`. The static binary will look for the `Caddyfile` in the directory where the `frankenphp run` command is executed. You can specify a custom path with the `-c` or `--config` option.
+In [the Docker images](docker.md), the `Caddyfile` is located at `/etc/frankenphp/Caddyfile`.
+The static binary will also look for the `Caddyfile` in the directory where the `frankenphp run` command is executed.
+You can specify a custom path with the `-c` or `--config` option.
 
 PHP itself can be configured [using a `php.ini` file](https://www.php.net/manual/en/configuration.file.php).
 
-By default, PHP supplied with Docker images and the one included in the static binary will look for a `php.ini` file in the directory where FrankenPHP is started and in `/usr/local/etc/php/`. They will also load all files ending in `.ini` from `/usr/local/etc/php/conf.d/`.
+The PHP interpreter will look in the following locations:
```
Comment (dunglas) [inline docs/config.md:11]:
```suggestion
Depending on your installation method, the PHP interpreter will look for configuration files in locations described above.
```

Comment (dunglas) [inline docs/config.md:11]:
```suggestion
Depending on your installation method, the PHP interpreter will look for configuration files in locations described above.
```

File: docs/config.md [hunk 23]
```diff
@@ -2,15 +2,20 @@
...
 
-No `php.ini` file is present by default, you should copy an official template provided by the PHP project.
+Docker:
```
Comment (dunglas) [inline docs/config.md:13]:
```suggestion
## Docker
```

File: docs/config.md [hunk 24]
```diff
@@ -2,15 +2,20 @@
...
 
-On Docker, the templates are provided in the images:
+- php.ini: `/usr/local/etc/php/php.ini` No php.ini is provided by default.
```
Comment (dunglas) [inline docs/config.md:15]:
```suggestion
- `php.ini`: `/usr/local/etc/php/php.ini` (no `php.ini` is provided by default)
```

File: docs/config.md [hunk 25]
```diff
@@ -2,15 +2,20 @@
...
+- additional configuration files: `/usr/local/etc/php/conf.d/*.ini`
+- php extensions: `/usr/local/lib/php/extensions/no-debug-zts-<YYYYMMDD>/`
```
Comment (dunglas) [inline docs/config.md:17]:
```suggestion
- PHP extensions: `/usr/local/lib/php/extensions/no-debug-zts-<YYYYMMDD>/`
```

File: docs/config.md [hunk 26]
```diff
@@ -22,7 +27,24 @@ RUN cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini
 RUN cp $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini
 ```
 
-If you don't use Docker, copy one of `php.ini-production` or `php.ini-development` provided [in the PHP sources](https://github.com/php/php-src/).
+dev.Dockerfile:
```
Comment (dunglas) [inline docs/config.md:30]: You can drop this section, or move it to `CONTRIBUTING.md`, `dev.Dockerfile` is only for contributors to FrankenPHP itself.

File: docs/config.md [hunk 27]
```diff
@@ -22,7 +27,24 @@ RUN cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini
...
+
+- php.ini: `/etc/frankenphp/php.ini` A php.ini file with development presets is provided by default.
+- additional configuration files: `/etc/frankenphp/php.d/*.ini`
+- php extensions: `/usr/lib/frankenphp/modules/`
+
+FrankenPHP installation (.rpm or .deb):
```
Comment (dunglas) [inline docs/config.md:36]:
```suggestion
## RPM and Debian packages
```

File: docs/config.md [hunk 28]
```diff
@@ -22,7 +27,24 @@ RUN cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini
...
+
+- php.ini: `/etc/frankenphp/php.ini` A php.ini file with production presets is provided by default.
```
Comment (dunglas) [inline docs/config.md:38]:
```suggestion
- `php.ini`: `/etc/frankenphp/php.ini` (a `php.ini` file with production presets is provided by default)
```

File: docs/config.md [hunk 29]
```diff
@@ -22,7 +27,24 @@ RUN cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini
...
+- additional configuration files: `/etc/frankenphp/php.d/*.ini`
+- php extensions: `/usr/lib/frankenphp/modules/`
```
Comment (dunglas) [inline docs/config.md:40]:
```suggestion
- PHP extensions: `/usr/lib/frankenphp/modules/`
```

File: docs/config.md [hunk 30]
```diff
@@ -22,7 +27,24 @@ RUN cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini
...
+
+Static binary:
```
Comment (dunglas) [inline docs/config.md:42]:
```suggestion
## Static binary
```

File: docs/config.md [hunk 31]
```diff
@@ -22,7 +27,24 @@ RUN cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini
...
+
+- php.ini: The directory in which `frankenphp run` or `frankenphp php-server` is executed, then `/etc/frankenphp/php.ini`
```
Comment (dunglas) [inline docs/config.md:44]:
```suggestion
- `php.ini`: The directory in which `frankenphp run` or `frankenphp php-server` is executed, then `/etc/frankenphp/php.ini`
```

File: docs/config.md [hunk 32]
```diff
@@ -22,7 +27,24 @@ RUN cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini
...
+- additional configuration files: `/etc/frankenphp/php.d/*.ini`
+- php extensions: cannot be loaded
```
Comment (dunglas) [inline docs/config.md:46]:
```suggestion
- PHP extensions: cannot be loaded, bundle them in the binary itself
```

File: package/Caddyfile [hunk 33]
```diff
@@ -0,0 +1,51 @@
+# The Caddyfile is an easy way to configure your Caddy web server.
```
Comment (dunglas) [inline package/Caddyfile:1]:
```suggestion
# The Caddyfile is an easy way to configure FrankenPHP and the Caddy web server.
```

File: package/Caddyfile [hunk 34]
```diff
@@ -0,0 +1,51 @@
...
+#
+# https://caddyserver.com/docs/caddyfile
+# https://frankenphp.dev/docs/config
```
Comment (dunglas) [inline package/Caddyfile:4]:
```suggestion
# https://frankenphp.dev/docs/config
# https://caddyserver.com/docs/caddyfile
```

**Review by dunglas — CHANGES_REQUESTED** [review]

File: build-packages.sh (hunk 19 above)
Comment (henderkes) [reply build-packages.sh:55]: Then the pull request CI wouldn't build packages and we might not realize when bugs are introduced.

**Comment by henderkes** [comment]
After thinking about it for a while, I've simplified the example project to just a php file without worker stuff. Also got rid of the environment variables to be more in line with other system installed packages (like caddy). 

image

File: package/content/example.php (hunk 7 above)
Comment (henderkes) [reply package/content/example.php]: I've reduced the demo files to one index.php and the two images. I've changed the frankenphp image to use [this](https://frankenphp.dev/img/logo_darkbg.svg) svg but with the white swapped to the purple from the other images.

File: package/Caddyfile (hunk 5 above)
Comment (henderkes) [reply package/Caddyfile]: I've removed the worker mode from the default Caddyfile. However, I still don't think it really makes sense to use the same Caddyfiles for docker and system packages. They just inherently incur different conventions.

File: package/Caddyfile [hunk 35]
```diff
@@ -0,0 +1,19 @@
+# The Caddyfile is an easy way to configure FrankenPHP and the Caddy web server.
+#
+# https://frankenphp.dev/docs/config
+# https://caddyserver.com/docs/caddyfile
+{
+	frankenphp
+}
+
+http://, https:// {
```
[the remark this answers is not in the document]
Comment (dunglas) [reply package/Caddyfile:9]: Let's do as the official packages.

[the remark this answers is not in the document]
Comment (henderkes) [reply package/Caddyfile]: Okay, I've removed https to follow Caddy's standards. I'm happy with the PR the way it's implemented then, for now. Next project would be to look into automating a package repository for .deb and .rpm packages and offer each php extension individually. We've merged dynamic extension building into it now so it's technically possible to build frankenphp with only core php and compile all extensions as shared libraries at the same time.

**Comment by henderkes** [comment]
I'm thinking about spinning up a static php package repository with static-php instead. Then we could build a shared libphp embed frankenphp and have the packages reply on php-zts instead.

**Comment by dunglas** [comment]
@henderkes should we wait for this or can we merge this PR now? I plan to draft a new release of FrankenPHP very soon. If it's ready for prime time, could you rebase against `main`, please?

**Comment by henderkes** [comment]
It's ready for release. It will take a significant amount of work to build repositories the way I envision it, so we're looking at a timeline of at least a month if I had to guess. Then we can look into coordinating shared frankenphp and static-php builds in the same repository.

I'll rebase tomorrow.

**Review by dunglas — APPROVED** [review]

**Comment by dunglas** [comment]
Thank you very much!! Great work.

**Comment by dunglas** [comment]
@henderkes it looks like the packages aren't uploaded successfully to the releases: https://github.com/dunglas/frankenphp/releases/tag/v1.6.0

**Comment by henderkes** [comment]
Hmm, indeed. I will look at the build logs to figure out what's going on.

**Comment by henderkes** [comment]
Oh, it looks like the action doesn't trigger on tagging a release. It uses some other workflow?

**Comment by henderkes** [comment]
@dunglas This unfortunately surpasses my docker knowledge a little. I'm not sure how to fix this without the possibility to trigger/test the workflow. 

It seems like it's looking for the image locally instead of the docker registry, but the image should be available in the docker registry after the build step.

```json
      "buildx.build.ref": "builder-3a2b0fd4-175c-493e-9dbd-0a7ca3fa6f0e/builder-3a2b0fd4-175c-493e-9dbd-0a7ca3fa6f0e0/hr0bmhjlm1azhgfbt0hapf157",
      "containerimage.descriptor": {
        "mediaType": "application/vnd.oci.image.index.v1+json",
        "digest": "sha256:3062e7f6e0eb72962f18b17dd6643d456235a1952cd2ca10617b34bcf6c1d6b2",
        "size": 856
      },
      "containerimage.digest": "sha256:3062e7f6e0eb72962f18b17dd6643d456235a1952cd2ca10617b34bcf6c1d6b2",
      "image.name": "***/frankenphp-dev"
```
Error:
```console
Unable to find image '***/frankenphp-dev@sha256:3062e7f6e0eb72962f18b17dd6643d456235a1952cd2ca10617b34bcf6c1d6b2' locally
Error response from daemon: toomanyrequests: You have reached your pull rate limit as '***': dckr_jti_RwLbnod8m96mttdDaz1YFCJDJ48=. You may increase the limit by upgrading. https://www.docker.com/increase-rate-limit
```

**Comment by henderkes** [comment]
https://github.com/mhpcc/frankenphp/blob/main/.github/workflows/create_custom_release.yaml#L46

This is how I work around it in my build with supervisor and cache, as I can't use the docker registry. I don't know if it would be intended to load them locally, though.
